[package]
name = "golly"
version = "0.1.0"
edition = "2021"
authors = ["William Tange <will@tan.ge>"]
repository = "https://github.com/s1gtrap/golly/"
license = "MIT OR Apache-2.0"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "life"
harness = false
